theme: jekyll-theme-minimal
title: Kirill Zhosul
logo: https://avatars.githubusercontent.com/u/79853674
description: <i>Programmer</i> - <i>Developer</i> <br><code>Web</code> • <code>Games</code> • <code>Apps</code> <br><code>GML</code> • <code>Python</code> • <code>C#</code><br>
